{
 "title": "Substrate Node Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node Instance",
    "query": "label_values(substrate_block_height, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{instance=~'$node'}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{instance='$node'}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket{instance='$node'}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{instance='$node'}[1m]) - rate(substrate_tasks_polling_duration_count{instance='$node'}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{instance='$node'}",
     "legendFormat": "Peers count"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{instance='$node'}",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_requested{instance='$node'}",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_peers{instance='$node'}",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "substrate_state_db_cache_bytes{instance='$node'}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{instance='$node'}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{instance='$node'}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{instance='$node'}",
     "legendFormat": "Queued Blocks"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{instance='$node'}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_number_leaves{instance='$node'}",
     "legendFormat": "Number of Leaves"
    }
   ]
  }
 ]
}